---
# tasks file for roles/hostname
- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  become: true

- name: Generate /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
  become: true
