* Hephaestus
Hephaestus is the affectionate name I gave my workstation. Named after the Greek god of engineering. This is the repo
I made to not only install my machine from scatch but to configure it and install the packages I use. The playbook in
this repo is designed to configure my linux machine from a bare system all the way up but due to ansible's idempotent
philosophy this playbook can be run at any point in the machines life to tweak things. This repo was inspired by
[[https://github.com/sudoforge/archer][archer]] by sudo forge on GitHub.

** Installation
If you are using this to install the entire system from scratch be sure to run the base.sh script to install a bare
arch linux filesystem. This script assumes you have your machine booting off of an arch linux iso and you can ssh to
the machine. If you already have a bare arch linux filesystem installed you can skip this step and run the ansible
playbook.

** Configuration
After you have gotten your base system installed this ansible playbook can be run on the machine.
