---
# tasks file for roles/packages
- name: Install Pacman packages
  community.general.pacman:
    name: "{{ pacman_packages }}"
    state: latest
  become: true

- name: Install aur package manager
  aur:
    name: "{{ aur_manager }}-bin"
    use: makepkg
    state: latest
  become: true
  become_user: "{{ aur_user }}"

- name: Install aur packages
  aur:
    name: "{{ aur_packages }}"
    use: "{{ aur_manager }}"
    state: latest
  become: true
  become_user: "{{ aur_user }}"
