---
# tasks file for roles/aur-packages
- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: "{{ aur_user }}"
    create_home: true
    group: wheel
  become: true

- name: Install aur package manager
  aur:
    name: "{{ aur_manager }}-bin"
    use: makepkg
    state: latest
  become: true
  become_user: "{{ aur_user }}"

- name: Install aur packages
  aur:
    name: "{{ aur_packages }}"
    use: "{{ aur_manager }}"
    state: latest
  become: true
  become_user: "{{ aur_user }}"
