---
# tasks file for roles/network
- name: Enable service dhcpcd
  ansible.builtin.systemd:
    name: dhcpcd
    enabled: true

- name: Enable service sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: true
  when: enable_sshd
