---
- name: Set root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password }}"
    update_password: always

- name: Set root password
  ansible.builtin.user:
    name: "{{ main_user }}"
    password: "{{ main_user_password }}"
    update_password: always
