---
# tasks file for roles/users
- name: Set root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password }}"
    update_password: always
  become: true
  when: set_root_password

- name: Check if aur user exists
  ansible.builtin.stat:
    path: "/home/{{ aur_user }}"
  register: aur_user_home

- name: Create aur user
  ansible.builtin.user:
    name: "{{ aur_user }}"
    groups: "{{ aur_user_groups }}"
    shell: /bin/fish
    update_password: on_create
  become: true
  when: aur_user_home.stat.isdir is not defined

- name: Check if main user exists
  ansible.builtin.stat:
    path: "/home/{{ main_user }}"
  register: main_user_home

- name: Clone my dotfiles
  ansible.builtin.git:
    repo: "https://github.com/maker2413/DotFiles.git"
    dest: "/home/{{ main_user }}"
  become: true

- name: Create main user
  ansible.builtin.user:
    name: "{{ main_user }}"
    groups: "{{ main_user_groups }}"
    password: "{{ main_user_password }}"
    shell: /bin/fish
    update_password: on_create
  become: true
  when: main_user_home.stat.isdir is not defined

- name: Change ownership of main user home directory
  ansible.builtin.file:
    path: "/home/{{ main_user }}"
    state: directory
    recurse: true
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
  become: true
  when: main_user_home.stat.isdir is not defined
