---
# tasks file for roles/users
# - name: Set root password
#   ansible.builtin.user:
#     name: root
#     password: "{{ root_password }}"
#     update_password: always

- name: Create main user
  ansible.builtin.user:
    name: "{{ main_user }}"
    groups: "{{ main_user_groups }}"
    password: "{{ main_user_password }}"
    shell: /bin/fish
    update_password: on_create
