---
# defaults file for roles/users
set_root_password: false

# Please don't use the default passwords
root_password: "{{ 'Password1!' | password_hash('sha512') }}"
main_user_password: "{{ 'Password1!' | password_hash('sha512') }}"
main_user: user
main_user_groups:
  - wheel
