---
# - name: Set Time Zone
#   ansible.builtin.file:
#     src: /usr/share/zoneinfo/{{ region }}/{{ location }}
#     path: /etc/localtime
#     state: link
#   become: true

- name: Run hwclock
  community.general.timezone:
    name: "{{ region }}/{{ location }}"
