---
- name: Create grub directory
  ansible.builtin.file:
    path: /boot/grub
    state: directory

- name: Run Grub Install
  ansible.builtin.command: grub-install --target=i386-pc /dev/{{ grub_disk }}
  when: install_grub and not efi

- name: Run Grub Install (EFI)
  ansible.builtin.command: grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
  when: install_grub and efi

# - name: Set grub default
#   ansible.builtin.lineinfile:
#     src:

- name: Check if grub.cfg needs to be created
  ansible.builtin.stat:
    path: /boot/grub/grub.cfg
  register: grub_config

- name: Write grub config file
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  when: not grub_config.stat.exists or remake_grub_config == "true"
